id: AF98DB493
title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
  Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace of
  the Dharmadhātu'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:59:54.271215
  last_modified_at: 2022-03-01 00:59:54.271219
